sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: lhshiwode
  wechat:
    appid: wx5e736e0b47a32a67
    secret: 6fd5cdf3c3055b58c77e1d4e905b1742
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 10



  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDqK7MgePmag1rqV7b9
    access-key-secret: rrClmPuzrcOOAoYAneUehbAtRdBEeo
    bucket-name: wqxqq