sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: lhshiwode
  wechat:
    appid: wx5e736e0b47a32a67
    secret: 6fd5cdf3c3055b58c77e1d4e905b1742
  redis:
    host: 8.134.200.99
    port: 6379
    password: qxxihuanwenlong
    database: 10

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDqK7MgePmag1rqV7b9
    access-key-secret: rrClmPuzrcOOAoYAneUehbAtRdBEeo
    bucket-name: wqxqq